name: Guideline checker

on:
  pull_request:
    branches:
      - master
    paths:
      - 'library/**'
      - 'projects/**'

jobs:
  guideline_check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          # version range
          python-version: '3.x'
      - name: Checkout repository code
        uses: actions/checkout@v3
        # repository that retrieves all the changed files
      - name: Load get-changed-files repo
        uses: Ana06/get-changed-files@v1.2
        id: changed_files
        with:
          format: space-delimited
      - name: Print changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed_files.outputs.all }}"
      - name: Execute py script for guideline check
        id: execution
        # -p flag means that files will be specified with their relative path
        run: |
          python ./.github/scripts/check_guideline.py -p ${{ steps.changed_files.outputs.all }}
        shell: sh
