name: Lint

on:
  pull_request:
    branches:
      - master
    paths:
      - 'library/**'
      - 'projects/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for Readme.md
        run: |
          bash ./.github/scripts/check_for_missing_readme_md.sh
